// Copyright 2026 Daher Alfawares
// SPDX-License-Identifier: LGPL-3.0-only

// Package one is the backend that apps generated by uione are built on.
//
// An app declares its entities as Go structs embedding Record, and its commands,
// views and roles as items of a Module. Serve runs them: commands arrive as
// POST /api/<namespace>/<entity>/<action> with a JSON body, are checked against
// who's asking and the entity's rules, and are written to Firestore in a
// transaction. Every write rebuilds the view documents that read it, which
// browsers read live and which the generated Firestore rules let each person read
// only when the document says they may.
//
// Apps don't usually use this package by hand: the uione compiler, one, writes
// the code that does.
package one
